import prettier from "eslint-config-prettier";
import { includeIgnoreFile } from "@eslint/compat";
import js from "@eslint/js";
import svelte from "eslint-plugin-svelte";
import globals from "globals";
import { fileURLToPath } from "node:url";
import ts from "typescript-eslint";
import importEslint from "eslint-plugin-import";
import { defineConfig } from "eslint/config";

const gitignorePath = fileURLToPath(new URL("./.gitignore", import.meta.url));

export default defineConfig(
    includeIgnoreFile(gitignorePath),
    js.configs.recommended,
    ...ts.configs.strict,
    ...ts.configs.stylistic,
    ...svelte.configs.recommended,
    prettier,
    ...svelte.configs.prettier,
    importEslint.flatConfigs.recommended,
    {
        languageOptions: {
            globals: { ...globals.node },
        },
        rules: {
            "prefer-arrow-callback": "error",
            "prefer-const": "error",
            "prefer-destructuring": [
                "error",
                {
                    VariableDeclarator: {
                        array: false,
                        object: true,
                    },
                    AssignmentExpression: {
                        array: false,
                        object: false,
                    },
                },
            ],
            "array-callback-return": "error",
            "no-duplicate-imports": ["error", { includeExports: true }],
            "no-self-compare": "error",
            "no-unreachable-loop": "warn",
            "block-scoped-var": "error",
            "consistent-return": "error",
            "consistent-this": "error",
            curly: ["error", "all"],
            "default-case": "error",
            "default-case-last": "error",
            "default-param-last": "off",
            eqeqeq: ["error", "always"],
            "func-name-matching": "error",
            "func-names": ["error", "as-needed"],
            "func-style": ["error", "expression"],
            "grouped-accessor-pairs": ["error", "getBeforeSet"],
            "logical-assignment-operators": [
                "error",
                "always",
                { enforceForIfStatements: true },
            ],
            "no-alert": "warn",
            "no-caller": "error",
            "no-div-regex": "error",
            "no-else-return": ["error", { allowElseIf: false }],
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-implicit-coercion": ["error", { boolean: false }],
            "no-implied-eval": "error",
            "no-iterator": "error",
            "no-label-var": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-multi-assign": "error",
            "no-negated-condition": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-wrappers": "error",
            "no-object-constructor": "error",
            "no-octal-escape": "error",
            "no-proto": "error",
            "no-return-assign": "error",
            "no-script-url": "error",
            "no-sequences": "error",
            "no-throw-literal": "error",
            "no-undef-init": "error",
            "no-unneeded-ternary": "error",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "no-void": "error",
            "object-shorthand": "error",
            "one-var": ["error", "never"],
            "operator-assignment": "error",
            "prefer-exponentiation-operator": "error",
            "prefer-numeric-literals": "error",
            "prefer-object-has-own": "error",
            "prefer-object-spread": "error",
            "prefer-promise-reject-errors": "error",
            "prefer-regex-literals": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            "require-await": "error",
            "require-unicode-regexp": "error",
            "symbol-description": "error",
            "vars-on-top": "error",
            yoda: "error",
            "@typescript-eslint/array-type": ["error", { default: "array" }],
            "@typescript-eslint/consistent-type-imports": [
                "error",
                { fixStyle: "inline-type-imports" },
            ],
            "@typescript-eslint/default-param-last": "error",
            "@typescript-eslint/method-signature-style": "error",
            "@typescript-eslint/no-dynamic-delete": "off",
            "@typescript-eslint/no-empty-function": "off",
            "@typescript-eslint/no-explicit-any": "warn",
            "@typescript-eslint/no-import-type-side-effects": "error",
            "@typescript-eslint/no-non-null-assertion": "warn",
            "no-shadow": ["error", { ignoreOnInitialization: true }],
            "@typescript-eslint/no-unnecessary-parameter-property-assignment":
                "error",
            "@typescript-eslint/no-useless-empty-export": "error",
            "@typescript-eslint/parameter-properties": "error",
            "@typescript-eslint/prefer-literal-enum-member": "warn",
            "@typescript-eslint/consistent-type-definitions": "off",
            "@typescript-eslint/no-unused-vars": [
                "error",
                { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
            ],
            "import/no-unresolved": "off",
            "import/newline-after-import": ["error", { count: 1 }],
            "import/order": [
                "error",
                {
                    groups: [],
                    "newlines-between": "never",
                },
            ],
        },
    },
    {
        files: ["**/*.svelte", "**/*.svelte.ts", "**/*.svelte.js"],
        languageOptions: {
            globals: { ...globals.browser },
            parserOptions: {
                projectService: true,
                extraFileExtensions: [".svelte"],
                parser: ts.parser,
            },
        },
        rules: {
            "no-undef-init": "off",
            "consistent-return": "off",
            "prefer-const": "off",
            "svelte/block-lang": ["error", { script: "ts", style: null }],
            "svelte/button-has-type": "error",
            "svelte/no-target-blank": "error",
            "svelte/no-ignored-unsubscribe": "error",
            "svelte/require-store-callbacks-use-set-param": "error",
            "svelte/no-at-html-tags": "off",
        },
    },
    {
        ignores: [
            "**/dist/*",
            "**/build/*",
            "**/drizzle/*",
            "**/node_modules/*",
            "**/.svelte-kit/*",
            "**/*.svx",
        ],
    }
);
